### ISSUE TITLE
A couple of fixes

### ISSUE THREAD

**Issue by sherakama** [irinaz/stanford_fellowship#1]
Thanks for this great work Irina. I have a couple of changes I would like to see.
1. Remove body field from field_bases
   Please remove the body field from the field_bases but keep it in the field_instances
2. Field naming consistency
   The field names should all start with `field_s_fellowship_`. Please ensure that they all do.
3. Please add descriptive text to the node type. 
   This should be a short description of what the content type is and does.
4. Please add description text to each field.
   Help text that shows up below each field is important to the end users.
5. Add a dependency to stanford_affiliate_organization
   This module has an entity dependency field that points to the stanford_affiliate_organization content type. Please add that as a dependency.

Great work! Keep it up.

**Comment by irinaz** [comment]
@sherakama 
Hi Shea, 
I have added a few changes based on Tori's feedback
1. Changed names for some fields
2. Made dates multiple value field
3. Added one more date field
4. Added Display Suite configuration 

Let me know if I should make updates in this issue.  Thanks, Irina

**Comment by sherakama** [comment]
@irinaz,

Thanks for letting me know about these changes. I think we can close this ticket now. We have adopted the module at: https://github.com/SU-SWS/stanford_fellowship. For the new work you want to get into the feature please send in a pull request to the SU-SWS account.

Thank you!
